spring.application.name=kafka-consumer-service
server.port=8092

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=vasanth-order-consumer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.vasanth.kafka.common
spring.kafka.consumer.properties.spring.json.value.default.type=com.vasanth.kafka.common.OrderCreatedEvent

app.kafka.order-topic=vasanth.orders.created
