spring.application.name=token-client-service
server.port=8081

okta.issuer-uri=https://your-okta-domain/oauth2/default
okta.client-id=your-client-id
okta.client-secret=your-client-secret
okta.scope=default

resource-service.url=http://localhost:8082/api/message
